### ISSUE TITLE
Add some validators to registration endpoint

### ISSUE THREAD

**Issue by ahnaf-zamil** [StackSurveyor/stacksurveyor-backend#4]
Right now, the `/user/register` endpoint only has 1 validator, and that is to check if the email exists in the DB or not.

We need 3 more validators to complete this endpoint:
  - A username validator to see if the username contains special characters or if it's bigger than 16 characters. The username limit should be 16 characters, just pointing it out.
  - An email validator which checks if the email is valid or not
  - A password validator to check if the password is at least 8 characters or not

**Comment by DevHyperCoder** [comment]
can i refactor the errorCode (which is Integer) to a ENUM ?

**Comment by ahnaf-zamil** [comment]
Yeah. I recommend you make a constants file for all the error codes. But make sure there's a class for each error-type (e.g UserError, SurveyError) because other types might share the same error codes. So the only way to differentiate them is to add them to a class for it's respective error type.

**Comment by DevHyperCoder** [comment]
Also, do you reckon we need to pass a string into the exception ? isnt the errror code enough ? 

in the client we can have the same enum right ?

**Comment by ahnaf-zamil** [comment]
Error code is not enough. We also need to pass a message. Here's how I implemented the `Email already exists` error:

```java
if (!Objects.isNull(existingUser)) {
    throw new UserException(1, "Email already exists", 400);
 }
```

The first argument is the error code. The 2nd argument is the error message, and the third argument is the HTTP status. If any of the validators for the registration endpoint is invalid, just use `400` (BAD_REQUEST).

**Comment by ahnaf-zamil** [comment]
Pr Merged, closing
